### ISSUE TITLE
Column class_label is missing

### ISSUE THREAD

**Issue by dathu** [hundredblocks/concrete_NLP_tutorial#10]
I am new to ML and NLP do we need to add the Column class_label.
I have downloaded from this link [https://www.figure-eight.com/data-for-everyone/](url)  pertaining to **Disasters on social media** as in your blog do help. Thanks in advance.

**Comment by CodyMWilson** [comment]
What is the goal of this project? @hundredblocks I'm looking for projects to contribute to.

**Comment by hundredblocks** [comment]
The relevant columns for the dataset are in `socialmedia_relevant_cols.csv`

This is a companion repository to this [blog post](https://blog.insightdatascience.com/how-to-solve-90-of-nlp-problems-a-step-by-step-guide-fda605278e4e?gi=3a71bd8cc092). You are welcome to contribute fixes to it but its structure mirrors that of the blog post.
