### ISSUE TITLE
keras.layers no longer has Merge in it.

### ISSUE THREAD

**Issue by hovikgas** [hundredblocks/concrete_NLP_tutorial#12]
It has been replaced by Concatenate, so the code will not run as is.

**Comment by hundredblocks** [comment]
Thanks for opening the issue @hovikgas . I've updated the code to use `Concatenate` instead, and took the opportunity to refresh word2vec download instructions to be more in line with recent gensim docs. 

I'll close the issue since this should fix it, feel free to reopen if that is not the case.
